name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: 
        echo "${{ secrets.DOCKERPW }}" | docker login -u "lijozech12" --password-stdin &&
        docker build -t lijozech12/train:latest . &&
        docker push lijozech12/train:latest
      
